language: ruby
rvm:
  - ruby-2.1

script:
  - ./script/cibuild.sh
bundler_args: "--without development"
cache:
  - bundler
notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
