name: Veterans.gov

#URL of site, include http://, do not include a trailing slash
#url: http://veterans.gov
url: http://localhost:4000


#files to exclude, array
exclude:
  - README.md
  - Rakefile
  - "/vendor/bundle"
  - Gemfile
  - Gemfile.lock
  - CNAME

#posts per page
paginate: 5

#number of items in RSS feed
rss_limit: 20

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:year/:month/:day/:title/

#whether production or dev, minifies JS, bool
production: true

#build config

timezone: America/New_York
encoding: UTF-8
safe: true

markdown: kramdown
timezone: America/New_York
encoding: UTF-8

kramdown:
  parse_block_html: true
  input: GFM

sass:
  sass_dir: _sass
  style: :compressed
  images_dir: 'img/content'
  javascripts_dir: 'assets/js'

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  # list all the collections here
  - disability
  - education
  - loans
  - health-care
  - pension
  - insurance
  - memorial
  - compensation
  - family


collections:
  # further define collections here
  disability:
    output: true
    permalink: /disability-benefits/:path/
  education:
    output: true
    permalink: /education/:path/
  loans:
    output: true
    permalink: /loans/:path/
  health-care:
    output: true
    permalink: /health-care/:path/
  pension:
    output: true
    permalink: /pension/:path/
  insurance:
    output: true
    permalink: /insurance/:path/
  memorial:
    output: true
    permalink: /memorial/:path/
  compensation:
    output: true
    permalink: /compensation/:path/
  family:
    output: true
    permalink: /family/:path/
